# TIPOS DE DADOS#

## NUMÉRICOS##

#### TIPOS INTEIROS:####

* Int8 — inteiros 8-bit com sinal variando de - 2^7 a 2^7 - 1.
* Int8 — inteiros 8-bit sem sinal variando de 0 a 2^8 - 1.
* Int16 — inteiros 16-bit com sinal variando de -2^15 a 2^15 - 1.
* Int16 — inteiros 16-bit sem sinal variando de 0 a 2^16 - 1.
* Int32 — inteiros 32-bit com sinal variando de -2^31 a 2^31 - 1.
* Int32 — inteiros 32-bit sem sinal variando de 0 a 2^32 - 1.
* Int64 — inteiros 64-bit com sinal variando de -2^63 a 2^63 - 1.
* Int64 — inteiros 64-bit sem sinal variando de 0 a 2^64 - 1.
* Int128 — inteiros 128-bit com sinal variando de -2^127 a 2^127 - 1.
* Int128 — inteiros 128-bit sem sinal variando de 0 a 2^128 - 1.
* Bool — valendo ou true (verdadeiro) ou false (falso), que correspondem numericamente a 1 ou 0, respectivamente.
* Char — um tipo numérico de 32 bits representando um caracter Unicode (veja Strings para mais detalhes).

#### TIPOS PONTO FLUTUANTE:####

* Float32 — Números de ponto flutuante 32-bit seguindo o padrão IEEE 754.
* Float64 — Números de ponto flutuante 64-bit seguindo o padrão IEEE 754.

#### NUMEROS COMPLEXOS ####

Para definir, usa-se a parte real em conjunto com a parte imaginária im

In [10]:
1 + 2im

1 + 2im

In [11]:
(1 + 8im) + (2 - 3im)

3 + 5im

In [12]:
(1 + 8im) * (2 - 3im)

26 + 13im

In [13]:
(26 + 13im)^2

507 + 676im

In [14]:
real(1 + 2im)

1

In [15]:
imag(1 + 2im)

2

In [16]:
conj(1 + 2im)

1 - 2im

In [17]:
abs(1 + 2im)

2.23606797749979

## CONSTANTES##

In [18]:
pi, e, golden

(π = 3.1415926535897...,e = 2.7182818284590...,φ = 1.6180339887498...)

<strong>Declarando uma constante</strong><br>
Constantes, declarado como <strong>const</strong>, são variáveis imutáveis quanto ao tipo. Ou seja, podem mudar de valor (será dado um aviso) mas não podem mudar de tipo.


In [19]:
# variável "vel_luz" do tipo string

const vel_luz = "299792458"

"299792458"

In [20]:
# Alterando a variável para outro valor do mesmo tipo string. Será dado um aviso

const vel_luz = "30000000"

"30000000"

In [21]:
# Não é possível alterar o tipo da variável "vel_luz" para inteiro. Ocorrerá ero

const vel_luz = 30000000

LoadError: LoadError: invalid redefinition of constant vel_luz
while loading In[21], in expression starting on line 3

In [22]:
vel_luz

"30000000"

In [23]:
# saber o tipo da constante

typeof(vel_luz)

ASCIIString

## VARIÁVEIS##

* ** Resetar todas as variáveis**

Julia não reseta, de fato, as variáveis. Na verdade ele configura outro workspace.

In [24]:
workspace()

* **Trabalhando com variáveis**

In [25]:
# Atribindo o valor 2 a variavel x

x = 2;

In [26]:
# Executando o calculo

x^2

4

In [27]:
# Variável literal

y = "so testando";

In [28]:
y

"so testando"

In [29]:
# Ao tentar utilizar uma variável nao declarada, ocorre um erro "Xvar not defined"

Xvar

LoadError: LoadError: UndefVarError: Xvar not defined
while loading In[29], in expression starting on line 3

In [30]:
# verificar o tipo da variável

typeof(x),typeof(y)

(Int64,ASCIIString)

In [31]:
# testar tipo

isa(x, Int64)

true

In [32]:
# construção de um complexo 

a = 2
b = 3.5

complex(a,b)

2.0 + 3.5im

* **Declarando  Várias variáveis ao mesmo tempo **

In [33]:
# Declarando Várias variáveis

x = 5 ; 
y = 10 ; 
z = "julia";

In [34]:
x,y,z

(5,10,"julia")

In [35]:
# Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis

w = begin
    x = 2
    y = 3
    x+y
    
end

5

In [36]:
# y do bloco de w

y

3

In [37]:
# outra forma. Por padrão, será impresso somente a ultima linha, mas as variáveis internas estão acessíveis

w = (x = 2; y = 3; x + y)

w

5

* ** Variáveis criadas ** 

In [38]:
whos()

                          Base  24768 KB     Module
                          Core   3194 KB     Module
                      LastMain  25563 KB     Module


## STRING##

** Convertendo uma string em uma expressão matemática **

In [39]:
string_formula = "x^2 + 1"

y = parse(string_formula)

:(x ^ 2 + 1)

In [40]:
typeof(y)

Expr

In [41]:
x = 0

eval(y)

1

## CONVERSÃO DE TIPOS##

<div style="text-align: justify;">Tabela de Tipos<br>
</div>
<table style="text-align: left; width: 271px; height: 304px;" border="1"
cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
<tr>
<td style="vertical-align: top;">a<br>
</td>
<td style="vertical-align: top;">a<br>
</td>
</tr>
</tbody>
</table>

In [42]:
a = 8;
b = 8.0;
c = "julia"

a,b,c

(8,8.0,"julia")

In [43]:
typeof(a), typeof(b), typeof(c)

                          Main   3197 KB     Module
                             a      8 bytes  Int64
                             b      8 bytes  Float64
                             w      8 bytes  Int64
                             x      8 bytes  Int64
                             y      8 bytes  Int64
                             z     13 bytes  ASCIIString


(Int64,Float64,ASCIIString)

In [44]:
d = Float64(a); e = convert(Int,b)

d , e

(8.0,8)

In [45]:
typeof(d),typeof(e)

(Float64,Int64)

## TUPLA##
Uma tupla é uma seqüência ordenada de elementos, como uma matriz. Uma tupla é representado por parênteses e vírgulas, em vez dos colchetes usados por matrizes. Tuplas são principalmente indicadas para agrupamento de comprimento fixo pequenas - eles são usados em todos os lugares em Julia, por exemplo, como listas de argumentos e de retorno de vários valores de funções.

A diferença importante entre matrizes e tuplas é que tuplas são <strong>imutáveis</strong>. Muitas funções de matrizes também pode ser usado em tuplas. Forma:

**variavel  = (valor1,valor2)** é do tipo inteiro, float, complex e outros.

In [46]:
t1 = (1,2,3)

(1,2,3)

In [47]:
typeof(t1)

Tuple{Int64,Int64,Int64}

In [48]:
t2 = (1,2,"Julia")

(1,2,"Julia")

In [49]:
typeof(t2)

Tuple{Int64,Int64,ASCIIString}

** Coisas para fazer com tuplas**

In [206]:
+(1,2,4), *(1,2,4)

(7,8)

## DICIONÁRIO ##

Os dicionários são estruturas de dados que contém pares de chave-valor. Diferente de um vetor no qual os valores do vetor é indexadas por numeros inteiros, dicionários são indexados por chaves (keys), que podem ser de qualquer tipo imutável (como strings e inteiros). Dicionários são delimitados por parenteses e contém uma lista de pares ("chave",valor) separada por vírgulas. Forma básica:

**Dict([(chave,valor),(chave,valor)]) ou Dict(chave => valor, chave => valor)** é do tipo Dict{"Tipo basico","Tipo basico"}

"Tipo basico" pode ser inteiro, Float, string, complex e any(valores heterogeneos).

In [1]:
d1 = Dict([("a", 1), ("b", 2),("c","Julia")])

Dict{ASCIIString,Any} with 3 entries:
  "c" => "Julia"
  "b" => 2
  "a" => 1

In [3]:
typeof(d1)

Dict{ASCIIString,Any}

outra forma mais compacta:

In [8]:
d2 = Dict(1 => "Maxima", 2 => 2, 3 =>"Julia")

Dict{Int64,Any} with 3 entries:
  2 => 2
  3 => "Julia"
  1 => "Maxima"

In [7]:
typeof(d2)

Dict{Int64,Any}

## CONJUNTOS##

Um Set é um conjunto de elementos, como uma matriz ou dicionário, sem elementos duplicados. Forma:

**Set{tipo_basico}(valor)**

tipo básico pode ser: inteiro, float, complex... ou any.

In [18]:
Coisas = Set(["Julia",10])

Set(Any[10,"Julia"])

In [20]:
in("Julia", Coisas)

true

## SEQUENCIAS##

Consiste de um conjunto ordenado de elementos,semelhante a um vetor, com cada elemento identificado por um índice. Forma:

** range(inicio,passo, tamanho)** é do tipo FloatRange{Float64}

In [52]:
# range(inicio, passo, tamanho)

vs1 = range(1, 0.1, 3)

typeof(vs1)

FloatRange{Float64}

In [53]:
# so vai até 3, se tentar o vs[4] ocorre erro

vs1[3]

1.2

In [54]:
vs2 = 1:0.1:3

typeof(vs2)

FloatRange{Float64}

In [55]:
vs2[3]

1.2

**Cuidado com os tipos! Veja a diferença**

In [56]:
r0 = range(1, 1  , 5)      # ranger do tipo inteiro
r1 = range(1, 1.0, 5)      # ranger do tipo float, observe o 1.0

display(r0)
display(r1)

display(typeof(r0))
display(typeof(r1))

1:1:5

1.0:1.0:5.0

StepRange{Int64,Int64}

FloatRange{Float64}

## LISTAS, ARRAY, VETORES E MATRIZES ##

### LISTAS E ARRAY###

Um array é uma coleção ordenada de elementos. É muitas vezes indicada com colchetes e itens separados por vírgulas. É possível criar arrays vazios ou arrays que armazenam valores de tipos diferentes ou restritas a valores de um tipo específico.

Na linguagem Julia, os arrays são usados para listas, vetores, tabelas e matrizes. Um array unidimensional atua como um vector ou uma lista. Uma array 2D pode ser utilizada como uma tabela ou matriz.

In [208]:
A1 = Array(Int,5)

5-element Array{Int64,1}:
          8589934594
          2147483649
                   0
                   0
 9042509406598427982

In [58]:
A2 = Array(AbstractString,5)

5-element Array{AbstractString,1}:
 #undef
 #undef
 #undef
 #undef
 #undef

In [59]:
A3 = Array(Float32,5)

5-element Array{Float32,1}:
 4148.81       
    4.58967e-41
 3951.26       
    4.58967e-41
 3940.25       

#### ARRAY UNIDIMENSIONAL/VETORES E ARRAY MULTIDIMENSIONAL/MATRIZES####

** Array Unidimensional / Vetores **

In [60]:
# Resetar todas a variáveis

workspace()

* ** Criação de vetores e acesso a dados em um vetor **

Para acessar um vetor utiliza a forma ** vetor[indice] **

In [61]:
# vetor coluna

a = [1, 2, 3, 4, 5]

# ou 

aa = [1;2;3;4;5]

display(a)
display(aa)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [62]:
# dimensoes do vetor

size(a) 

(5,)

In [63]:
# Vetor Linha

b = [1 2 3 4 5]

1x5 Array{Int64,2}:
 1  2  3  4  5

In [64]:
# dimensoes do vetor

size(b) 

(1,5)

In [65]:
# transforma o vetor linha ou array (matrix de 1x5 (2 dimensoes)) em um vetor de uma dimensão

bb = vec(b)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [66]:
# array de 2 dimensões e agora vetor de 1 dimensão

typeof(b), typeof(bb)

(Array{Int64,2},Array{Int64,1})

* **Manipulação de Arrays/vetores **

In [67]:
# vetor vazio

a = []

0-element Array{Any,1}

In [68]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(a)

0

In [69]:
# adicionando o elemento 10 e em seguida os elementos -2, -4, 500 e 100 ao final do vetor

push!(a,10), push!(a,-2,-4,500,100)

(Any[10,-2,-4,500,100],Any[10,-2,-4,500,100])

In [70]:
# retirando elemento do final do vetor 

pop!(a), a

(100,Any[10,-2,-4,500])

In [71]:
# retirar elemento de uma posição específica. deleteat!(vetor,posição)

deleteat!(a,3)

3-element Array{Any,1}:
  10
  -2
 500

In [72]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor). 
# No exemplo, o vetor [100 1] é colocado na posição 2

splice!(a, 2, [100 1]),a

(-2,Any[10,100,1,500])

In [73]:
# fatia o vetor na forma splice!(vetor,faixa de posições ou apenas uma posição,novo_vetor).
# no exemplo, o vetor [50 -50] é inserido entre as posições 2 a 4

splice!(a, 2:4, [50 -50]), a

(Any[100,1,500],Any[10,50,-50])

In [74]:
# Aumentar o tamanho do vetor em 10 posições #undef significa tipo indefinido

resize!(a,10)

10-element Array{Any,1}:
  10   
  50   
 -50   
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [75]:
# Limpar o vetor 

empty!(a), a

(Any[],Any[])

* ** Vetor aleatorio e vetor vazio indefinido**

In [76]:
va = rand(3)

3-element Array{Float64,1}:
 0.631419
 0.389091
 0.563389

In [77]:
# CUIDADO COM OS TIPOS! VEJA A DIFERENÇA

v0 = rand(3)       # vetor unidimensional do tipo float
v1 = rand(3,1)     # vetor bidimensional do tipo float

display(v0)
display(v1)

display(size(v0))
display(size(v1))

display(size(v0))
display(size(v1))

3-element Array{Float64,1}:
 0.406557
 0.118998
 0.27686 

3x1 Array{Float64,2}:
 0.72444 
 0.573554
 0.263915

(3,)

(3,1)

(3,)

(3,1)

In [181]:
# vetor de tipo definido com dados gerados aleatoriamente

b = Array(Int64,3)

3-element Array{Int64,1}:
 140588692488400
 140588683518416
 140588683511120

In [79]:
# acessar dado e um vetor

b[2]

2147483649

In [80]:
# dimensoes do vetor

size(b)

(1,3)

In [81]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(b)

3

In [82]:
# push e pop nao serve para vetores linha! Funciona somente para vetores coluna.

push!(b,10), pop!(b)

LoadError: LoadError: MethodError: `push!` has no method matching push!(::Array{Int64,2}, ::Int64)

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.
Closest candidates are:
  push!(::Any, ::Any, !Matched::Any)
  push!(::Any, ::Any, !Matched::Any, !Matched::Any...)
  push!(!Matched::Array{Any,1}, ::ANY)
  ...
while loading In[82], in expression starting on line 3

In [83]:
# vetor de tipo indefinido vazio

c = cell(1, 3)

1x3 Array{Any,2}:
 #undef  #undef  #undef

Informação sobre o tipo do vetor e tipo dos elementos

In [84]:
# tipo do vetor e tipo dos elementos do vetor

typeof(b),eltype(b)

(Array{Int64,2},Int64)

* ** Criando vetores de zeros e uns **

In [85]:
# vetor de zeros

d = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [86]:
# vetor de uns

e = ones(5)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [87]:
# CUIDADO COM OS TIPOS! VEJA A DIFERENÇA

e0 = ones(3)       # vetor unidimensional do tipo float
e1 = ones(3,1)     # vetor bidimensional do tipo float
e2 = ones(1:3)     # vetor unidimensional do tipo inteiro
e3 = ones(1.0:3.0) # vetor unidimensional do tipo float

display(e0)
display(e1)
display(e2)
display(e3)

display(size(e0))
display(size(e1))
display(size(e2))
display(size(e3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

3x1 Array{Float64,2}:
 1.0
 1.0
 1.0

3-element Array{Int64,1}:
 1
 1
 1

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

(3,)

(3,1)

(3,)

(3,)

* ** Criando vetores usando o linspace(incio, fim, partes) **

In [88]:
# Criando um vetor de 1 a 2 com 5 partes

x = linspace(1, 2, 5);

x   # hehehe nao mostra os dados

linspace(1.0,2.0,5)

In [89]:
# dimensoes e tipo do vetor

size(x), typeof(x)

((5,),LinSpace{Float64})

In [90]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(x)

5

In [91]:
# acessando dados no vetor x

x[1],x[2],x[3],x[4],x[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando o collect(inicio: passo: fim) **

In [92]:
# Criando um vetor de 1 a 2 de 0.25 em 0.25

y = collect(1:0.25:2) 

5-element Array{Float64,1}:
 1.0 
 1.25
 1.5 
 1.75
 2.0 

In [93]:
# dimensoes do vetor

size(y)

(5,)

In [94]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(y)

5

In [95]:
# acessando dados no vetor y

y[1],y[2],y[3],y[4],y[5]

(1.0,1.25,1.5,1.75,2.0)

In [96]:
# CUIDADOS COM OS TIPO! VEJA A DIFERENÇA

y0 = collect(1:2:6)   # vetor unidimensional do tipo inteiro
y1 = collect(1.0:2:6) # vetor unidimensional do tipo float
y2 = collect(1:2.0:6) # vetor unidimensional do tipo float

display(y0)
display(y1)
display(y2)

display(size(y0))
display(size(y1))
display(size(y2))

3-element Array{Int64,1}:
 1
 3
 5

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

3-element Array{Float64,1}:
 1.0
 3.0
 5.0

(3,)

(3,)

(3,)

* ** Criando vetores usando o range {inicio: passo: fim} **

In [97]:
# semelhante ao linspace do MatLab

z = 1:0.25:2

1.0:0.25:2.0

In [98]:
# acessando dados no vetor z

z[1],z[2],z[3],z[4],z[5]

(1.0,1.25,1.5,1.75,2.0)

* ** Criando vetores usando o preenchimento **

In [99]:
# cria um vetor de 5 elementos preenchidos com a letra a string julia

t = fill("julia", 1, 5)

1x5 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"  "julia"  "julia"

In [100]:
# tipo do vetor e tipo dos elementos do vetor

typeof(t),eltype(t)

(Array{ASCIIString,2},ASCIIString)

In [101]:
# quantidade de elementos de um vetor ou tamanho do vetor

length(t)

5

* **Redimensionando vetores **

In [102]:
# resize!(vetor,x) Redefine um vetor para um tamanho "x". 
# Se o tamanho do vetor for menor que o tamanho "x", é feito o preenchimento adicional 
# de mais elementos aleatoriamente ao final do vetor.

# y é um vetor coluna de 1 até 2 de 0.5 em 0.5, de tamanho 4.

y = collect(1:0.5:2); 

p = resize!(y,5)

5-element Array{Float64,1}:
 1.0
 1.5
 2.0
 0.0
 0.0

* ** Acessos especiais **

In [103]:
v = [1, 2, 3, 4, 5,6,7,8,9,10,11,12,13,14,15];

u = ["a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "l" "m" "n" "o" "p"];

In [104]:
# imprime os elementos a partir do elemento 1 até o ultimo (end) de 2 em 2 

v[1:2:end] , u[1:2:end] 

([1,3,5,7,9,11,13,15],ASCIIString["a","c","e","g","i","l","n","p"])

In [105]:
# imprime os elementos a partir do elemento 5 até o ultimo (end) de 2 em 2 

v[5:2:end] ,u[5:2:end] 

([5,7,9,11,13,15],ASCIIString["e","g","i","l","n","p"])

In [106]:
# imprime na forma de um vetor coluna, os elementos de ordem primeiro, terceiro e sexto

v[[1, 3, 6]], u[[1, 3, 6]]

([1,3,6],ASCIIString["a","c","f"])

In [107]:
# imprime na forma de um vetor linha, os elementos de ordem primeiro, terceiro e sexto

v[[4 5 6]], u[[4 5 6]]

(
1x3 Array{Int64,2}:
 4  5  6,

1x3 Array{ASCIIString,2}:
 "d"  "e"  "f")

In [108]:
# cria um subconjunto coluna do vetor do elemento de posição 1 até o elemento de posição 10 
# tomando de 2 em 2 posições

sub(v, 1:3:10), sub(u, 1:2:10)

([1,4,7,10],ASCIIString["a","c","e","g","i"])

In [109]:
# posição final do vetor

endof(v), endof(u)

(15,15)

* **Concatenação de vetores **

In [110]:
# concatenação de vetores

tta = [1 2 3 ];
ttb = [4 5 6];

z = [tta ttb]   # cria um vetor linha
x = [tta ; ttb] # cria uma matriz 3x2

z, x

(
1x6 Array{Int64,2}:
 1  2  3  4  5  6,

2x3 Array{Int64,2}:
 1  2  3
 4  5  6)

* ** Ordenação de vetores **

In [1]:
# ordenando vetor

va = rand(5); 

println("vetor normal :",va);

println("vetor ordenado :",sort(va));

vetor normal :[0.7649444053803092,0.059301936050308646,0.7931547650581892,0.26535306170407047,0.26811184082072237]
vetor ordenado :[0.059301936050308646,0.26535306170407047,0.26811184082072237,0.7649444053803092,0.7931547650581892]


* **Filtro**

In [2]:
vet = 1:10

filter(x -> x % 2 == 0, vet)

5-element Array{Int64,1}:
  2
  4
  6
  8
 10

In [11]:
vet_nomes = ["julia","sage","maxima","julia","scilab","julia"]

filter(x -> x != "julia", vet_nomes)

3-element Array{ASCIIString,1}:
 "sage"  
 "maxima"
 "scilab"

* **criar par de elementos**

In [137]:
vet_a = [8.4 9.5 10.6]
vet_b = [8.1 9.2 10.3]

pares = zip(vet_a,vet_b)

Base.Zip2{Array{Float64,2},Array{Float64,2}}(1x3 Array{Float64,2}:
 8.4  9.5  10.6,1x3 Array{Float64,2}:
 8.1  9.2  10.3)

In [129]:
typeof(pares)

Base.Zip2{Array{Float64,2},Array{Float64,2}}

In [130]:
for i in pares
    print(i)    
end

(8.4,8.1)(9.5,9.2)(10.6,10.3)

#### ARRAY MULTIDIMENSIONAL / MATRIZES####

* **Criação e manipulação de Matrizes**

In [112]:
#Criando uma matriz 3x3 

M = [2 4 6;8 9 10;12 14 16]

3x3 Array{Int64,2}:
  2   4   6
  8   9  10
 12  14  16

In [113]:
# criando matriz de valores aleatórios

Ma = rand(3,3)

3x3 Array{Float64,2}:
 0.327365  0.859842  0.795062
 0.96991   0.113485  0.546973
 0.966297  0.351106  0.114792

In [114]:
# criando uma matriz Mb 3x3 e testando se os elementos 2 e 15 fazem parte da matriz

Mb = [2 4 6;8 9 10;12 14 16]

(2 in Mb),(in(15, Mb))

(true,false)

In [115]:
# listar elentos impareres da matriz Mb

find(iseven, Mb)

[0.2710342052268504,0.3679448493238391,0.6835151370914729,0.7157669964612825,0.7414832987785993]


8-element Array{Int64,1}:
 1
 2
 3
 4
 6
 7
 8
 9

In [116]:
# devolve os índices dos elementos de matriz "A", onde os elementos podem ser encontrados:

println(Mb)

println()

println(findin(Mb, [2,6]))

[2

In [117]:
# cria uma matriz formada pelos numeros de 1 a 9 sorteados aleatoriamente de tamanho 3x3

Mad = rand(1:9, 3, 3)

3x3 Array{Int64,2}:
 1  6  3
 7  9  2
 7  8  8

In [118]:
# jogos da mega sena parte 2: penultimate edition!

Mad = rand(1:60, 6, 6)

6x6 Array{Int64,2}:
 43  59  41  53  22   8
 59  24  47  42  16  46
 19  60  47  16  47  27
 20  11  60  41  43   4
 29  29  54  49  35  19
 14  41  49  54  28   8

* ** Ordenação de elementos **

In [119]:
# ordena as linhas 

sortrows(Mad)

6x6 Array{Int64,2}:
 14  41  49  54  28   8
 19  60  47  16  47  27
 20  11  60  41  43   4
 29  29  54  49  35  19
 43  59  41  53  22   8
 59  24  47  42  16  46

 4 6
 8 9 10
 12 14 16]

[1,7]


In [120]:
# ordena as colunas

sortcols(Mad)

6x6 Array{Int64,2}:
  8  22  41  43  53  59
 46  16  47  59  42  24
 27  47  47  19  16  60
  4  43  60  20  41  11
 19  35  54  29  49  29
  8  28  49  14  54  41

* ** Matrizes de zeros e uns **

In [121]:
# cria uma matriz 3x3 de zeros

Mz = zeros(3,3)

3x3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [122]:
# cria uma matriz 3x3 de uns

Mo = ones(3,3)

3x3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [123]:
# cria uma matriz 3x3 identidade

Mi = eye(3, 3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

* ** Preenchimento de matrizes **

In [124]:
# Cria uma matriz 3x3 preenchendo (fill) de strings "julia"

Mf = fill("julia", 3, 3)

3x3 Array{ASCIIString,2}:
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"
 "julia"  "julia"  "julia"

In [125]:
# cria uma matriz repetindo a matriz 3x3 .....

repmat(ones(3), 4, 2)

12x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [126]:
# 

reshape(linspace(0, 100, 30), 10, 3)

10x3 Array{Float64,2}:
  0.0      34.4828   68.9655
  3.44828  37.931    72.4138
  6.89655  41.3793   75.8621
 10.3448   44.8276   79.3103
 13.7931   48.2759   82.7586
 17.2414   51.7241   86.2069
 20.6897   55.1724   89.6552
 24.1379   58.6207   93.1034
 27.5862   62.069    96.5517
 31.0345   65.5172  100.0   

**Repetindo elementos para preencher matrizes**

Duas funções úteis para a criação de matrizes: são repmat (A, n, m) e repeat().

    A -> matriz
    n,m -> quantidade de repetições para n linhas e m colunas 

In [11]:
A = [1 2 3;4 5 6]

2x3 Array{Int64,2}:
 1  2  3
 4  5  6

In [12]:
# será repetido as colunas 3x e 2x as colunas

repmat(A, 3, 2)

6x6 Array{Int64,2}:
 1  2  3  1  2  3
 4  5  6  4  5  6
 1  2  3  1  2  3
 4  5  6  4  5  6
 1  2  3  1  2  3
 4  5  6  4  5  6

* **Criação de matrizes a partir da concatenação de vetores **

In [128]:
v1 = [1 2 3]
v2 = [1,2,3]

display(v1)
display(v2)

1x3 Array{Int64,2}:
 1  2  3

3-element Array{Int64,1}:
 1
 2
 3

In [129]:
# matriz 1x6 

Mv1 = [v1 v1]

1x6 Array{Int64,2}:
 1  2  3  1  2  3

In [130]:
# matriz 3x2 

Mv2 = [v2 v2]

3x2 Array{Int64,2}:
 1  1
 2  2
 3  3

In [131]:
# matriz 2x3

Mv3 = [v1 ; v1]

2x3 Array{Int64,2}:
 1  2  3
 1  2  3

In [132]:
# matriz 6x1 

Mv4 = [v2 ; v2]

6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

* ** Concatenação de matrizes**

In [133]:
Mra = [1 2 3 ; 4 5 6 ]; 
Mrb = [0 0 0;1 1 1];

Mra, Mrb

(
2x3 Array{Int64,2}:
 1  2  3
 4  5  6,

2x3 Array{Int64,2}:
 0  0  0
 1  1  1)

In [134]:
display([Mra Mrb])

display([Mra;Mrb])

2x6 Array{Int64,2}:
 1  2  3  0  0  0
 4  5  6  1  1  1

4x3 Array{Int64,2}:
 1  2  3
 4  5  6
 0  0  0
 1  1  1

In [135]:
# imprimir todos os elementos da segunda coluna da matriz Mra
display(Mra[:,2])

# imprimir todos os elementos da segunda linha da matriz Mrb
display(Mrb[2,:])

2-element Array{Int64,1}:
 2
 5

1x3 Array{Int64,2}:
 1  1  1

In [193]:
# 

[Mra[:,2] Mrb]

LoadError: LoadError: UndefVarError: Mra not defined
while loading In[193], in expression starting on line 3

* **Filtro aplicado a uma matriz**

In [18]:
mat_num = rand(3,3)
display(mat_num)

filter(x -> x <= 0.2, mat_num)

3x3 Array{Float64,2}:
 0.340955   0.380597  0.826276
 0.38772    0.034579  0.212642
 0.0317899  0.948366  0.399439

2-element Array{Float64,1}:
 0.0317899
 0.034579 

## POLINOMIOS##

In [174]:
using SymPy
@syms x

(x,)

In [175]:
P = Poly(x^2 - 4, x)

Poly(x**2 - 4, x, domain='ZZ')

In [8]:
coeffs(P)

2-element Array{Any,1}:
  1
 -4

## TIPOS DEFINIDOS PELO PROGRAMADOR##

In [137]:
type Forca
    massa     ::Float64
    Aceleracao::Float64    
end

In [138]:
typeof(Forca)

DataType

In [139]:
objeto1 = Forca(5,0.1)

Forca(5.0,0.1)

In [140]:
typeof(objeto1)

Forca

In [141]:
fieldnames(objeto1)

2-element Array{Symbol,1}:
 :massa     
 :Aceleracao

In [142]:
objeto1.massa, objeto1.Aceleracao

(5.0,0.1)

In [143]:
type Aluno
    Nome    ::AbstractString
    Sexo    ::AbstractString
    Idade   ::Int64
    Endereco::AbstractString
end

In [144]:
J1 = Aluno("Julia","F",18,"Rua MIT,2001")

Aluno("Julia","F",18,"Rua MIT,2001")

In [145]:
typeof(J1)

Aluno

In [146]:
fieldnames(J1)

4-element Array{Symbol,1}:
 :Nome    
 :Sexo    
 :Idade   
 :Endereco

In [147]:
J1.Nome

"Julia"

In [148]:
J1.Idade

18

%%% Fim Tipos de Dados %%%