# PROGRAMAÇÃO BÁSICA#

## OPERADORES LÓGIGOS E BOLEANOS ##

Operadores de comparação para determinar, por exemplo, se são iguais. Todos os operadores de comparação da JULIA retornam TRUE como verdade e FALSE como falso.
Resumo:

    * x < y     verdade se x é menor que y.

    * x <= y   verdade se x é menor ou igual a y.

    * x >= y   verdade se x é maior ou igual a y.

    * x > y    verdade se x é maior que y.

    * x == y   verdade se x é igual a y.

    * x != y   verdade se x diferente de y

    * x ~= y   verdade se x é diferente de y.

Uma expressão booleana elemento por elemento, é uma combinação de comparação de expressões usando os operadores:

    * ||, operador “ou”

    * &&, operador “e”

    * ~ ou !, operador “não”

Uma expressão booleana é verdadeira se o resultado do cálculo das combinações lógicas das expressões booleanas for verdadeira. O valor será considerado falso se for zero, e verdadeiro de outra forma.


## ESTRUTURAS DE CONTROLE ##

Laços ocupam um lugar relevante no controle e núcleos de repetição. Os comandos de controle
de laço são: while, for, do, if, switch

### CONDICIONAL "SE" (IF) ###

<p style="text-align: justify;"><strong>Condicional IF</strong></p>
<p style="text-align: justify;"><strong></strong></p>
<table style="text-align: left; width: 359px; height: 186px; margin-left: 0px; margin-right: 0px;" border="1" cellpadding="2" cellspacing="1">
<tbody>
<tr>
<td style="vertical-align: top; text-align: left;"><span style="font-weight: bold;">if</span> condição<br>
&nbsp;&nbsp;&nbsp;
instruções<br>
&nbsp;<span style="font-weight: bold;">end</span></td>
<td style="vertical-align: top;">&nbsp;<span style="font-weight: bold;">if </span>condição<br>

&nbsp;&nbsp;&nbsp;
instruções<span style="font-weight: bold;"></span><br>
&nbsp;<span style="font-weight: bold;">else</span><br>
&nbsp;&nbsp;&nbsp;
instruções<br>
&nbsp;<span style="font-weight: bold;">end</span></td>
<td style="vertical-align: top;">&nbsp;<span style="font-weight: bold;">if</span> condição<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<span style="font-weight: bold;"></span><br>

&nbsp;<strong>elseif</strong> outra_condição<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<span style="font-weight: bold;"></span><br>
&nbsp;<span style="font-weight: bold;">else</span><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; outro_bloco_ainda<span style="font-weight: bold;"></span><br>
&nbsp;<span style="font-weight: bold;">end</span> 
</td>
</tr>

</tbody>
</table>

In [4]:
x=rand(0:10)

y=rand(0:10)

x,y

(6,10)

In [5]:
# se x< 15 será impresso a mensagem, se x>y não será feito nada

if x < y
    println("x é menor que y")
end

x é menor que y


Melhorando....

In [165]:
if x < y
    println("x é menor que y .","Valor de x: ",x," Valor de y: ",y)
else
    println("x é maior que y .","Valor de x: ",x," Valor de y: ",y)
end

x é menor que y .Valor de x: 6 Valor de y: 9


Melhorando mais....

In [166]:
if x < y
  println("x é menor que y .","Valor de x: ",x," Valor de y: ",y)
    
elseif x > y
  println("x é maior que y .","Valor de x: ",x," Valor de y: ",y)
    
else
    println("x é igual a y .","Valor de x: ",x," Valor de y: ",y)
end

x é menor que y .Valor de x: 6 Valor de y: 9


 Definindo funções do tipo: $~
f(x) = \begin{cases}
\cos(x) & x \geq 0\\
1 - e^{-1/x^2} & \text{x < 0}.
\end{cases}
~$

In [167]:
x  = rand(-1:1)

if x>=0
    print("f = cos(x) = ",cos(x))
    
elseif x<0
    print("f = exp(-1/x^2) = ",exp(-1/x^2))
    
end

f = exp(-1/x^2) = 0.36787944117144233

** OPERADOR TERNÁTIO (“ternary operator")  **

O chamado "operador ternário",(:?), Está relacionado com a sintaxe if-elseif-else, recebe este nome em função de ser o único operador na maioria dos idiomas que tomam três operandos:
**(condição ? expressão1 : expressão2)**

A operação ternária efeturá a **"expressão1"** antes do ":" se a **"condição"** é verdadeira ou a **"expressão2"** depois do ":" se "condição" for falsa

In [5]:
ot(x) = ( x >= 0 ? sqrt(x) : "Raiz de numero negativo")

ot (generic function with 1 method)

In [6]:
ot(8) , ot(-2)

(2.8284271247461903,"Raiz de numero negativo")

### CONDICIONAL "TROCAR" (SWITCH) ###

Não existe um comando nativo para "case" ou "swith". Pode ser utilizado uma sequencia de "if..elseif..else" ou instalar o "case" do pacote "Switch"

<p style="text-align: justify;"><strong>Condicional "SWITCH"</strong></p>
<p style="text-align: justify;"><strong></strong></p>
<table style="text-align: left; width: 440px; height: 335px; margin-left: 0px; margin-right: 0px;" border="1" cellpadding="2" cellspacing="1">
<tbody>
<tr>
<td colspan="1" rowspan="1" style="vertical-align: top; text-align: left;"><span style="font-weight: bold;">if </span>variável<span style="font-weight: bold;">&nbsp;</span> condição <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<br>&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">elseif </span>variável<span style="font-weight: bold;">&nbsp;</span> condição<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<br>&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">elseif</span> variável<span style="font-weight: bold;">&nbsp;</span> condição<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<br><span style="font-weight: bold;">end</span> 

</td><td style="vertical-align: top;"><span style="font-weight: bold;">using Switch</span><br>variável condição<br>&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">@switch</span> variável begin<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">@case</span> valor variável<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">break</span><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">@case</span> valor variável<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instruções<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">break</span><br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">@default</span><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; println("Não encontrado")<span style="font-weight: bold;"></span><br><span style="font-weight: bold;">end</span></td>

</tr>
</tbody>
</table>

In [2]:
x = rand(-10:10)
y = sin(x)

if  y == 0
    print("Raiz: ",x) 
    
elseif y > 0
    print("Valor positivo: ",y,". valor de x: ",x)
    
elseif y < 0 
    print("Valor negativo: ",y,". valor de x: ",x)    

end


Valor positivo: 0.1411200080598672. valor de x: 3

In [6]:
using Switch

y = rand(0:4)

@switch y begin
    @case 0
    print( "y vale Zero")
    break

    @case 1
    println("y vale Um")
    break

    @case 2
    println("y vale Dois")
    break

    @default
    println("Não encontrado.numero acima de 2")
end

y vale Zero

### REPETIÇÃO "PARA" (FOR) ###

<strong>Repeti&ccedil;&atilde;o "FOR" </strong>

<table style="text-align: left; width: 417px; height: 156px; margin-left: 0px; margin-right: 0px;" border="1" cellspacing="1" cellpadding="2">
<tbody>
<tr>
<td style="vertical-align: top; text-align: left;" colspan="1" rowspan="1">&nbsp;<span style="font-weight: bold;">for</span> vari&aacute;vel = inicio : fim<br /> &nbsp;&nbsp;&nbsp;&nbsp; instru&ccedil;&otilde;es<span style="font-weight: bold;">;</span><br /> &nbsp;<span style="font-weight: bold;">end</span><br /> &nbsp;</td>
<td style="vertical-align: top;"><span style="font-weight: bold;">for</span> vari&aacute;vel <span style="font-weight: bold;">in = range</span><br /> &nbsp;&nbsp;&nbsp;&nbsp; instru&ccedil;&otilde;es<span style="font-weight: bold;">;</span><br /> &nbsp;<span style="font-weight: bold;">end</span><br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</td>
</tr>
<tr>
<td style="vertical-align: top; text-align: left;"><strong>for</strong> vari&aacute;vel = inicio : length(vetor)<br /> &nbsp;&nbsp;&nbsp;&nbsp; instru&ccedil;&otilde;es;<br /><strong>end</strong></td>
<td style="vertical-align: top;">&nbsp;<strong>for</strong> vari&aacute;vel = inicio : fim<br /> &nbsp;&nbsp;&nbsp;&nbsp; instru&ccedil;&otilde;es;<br /> &nbsp;&nbsp;&nbsp;&nbsp; <strong>if</strong> condi&ccedil;&atilde;o<br /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>continue ou break</strong><br /> &nbsp;&nbsp;&nbsp;&nbsp; <strong>end</strong><br /> &nbsp;<strong>end</strong></td>
</tr>
</tbody>
</table>

In [1]:
print("Valor da função sin(x)*cos(x/2)+x: \n\n")

for x = [1 2 3 4 5] # pode ser também x in vetor
    
    println(sin(x)*cos(x/2)+x," Para x = ",x)
    
end

Valor da função sin(x)*cos(x/2)+x: 

1.7384602626041288 Para x = 1
2.491295496433882 Para x = 2
3.0099824344694786 Para x = 3
4.314940964313378 Para x = 4
5.768236060439348 Para x = 5


In [2]:
vetor = 1:5

print("Valor da função sin(x)*cos(x/2)+x:\n\n")

for x = vetor # pode ser usando também x = 1:length(vetor) ou x in vetor
    
    println(sin(x)*cos(x/2)+x," Para x = ",x)
    
end
    

Valor da função sin(x)*cos(x/2)+x:

1.7384602626041288 Para x = 1
2.491295496433882 Para x = 2
3.0099824344694786 Para x = 3
4.314940964313378 Para x = 4
5.768236060439348 Para x = 5


** Break e Continue **

In [172]:
# para i de 1 até 10,
# se o resto da divisão i por 3 for diferente de zero, 
# então o loop é parado e retorna para o inicio do FOR
# e o loop será continuado até o final se o resto for 0

for i = 1:10
    if i % 3 != 0
        continue
    end
    println(i)
end


3
6
9


In [173]:
# para i de 1 até 10,
# se o resto da divisão i por 3 for igual a zero,então o loop é encerrado

for i = 1:10
    if i % 3 == 0
        break
    end
    println(i)
bend


1
2


** Controlando o laço For com sleep**

Importe o pacote PyPlot e use o comando **sleep(tempo_segundos)**

In [17]:
vetor = 1:5

print("Valor da função sin(x)*cos(x/2)+x:\n\n")

for x = vetor # pode ser usando também x = 1:length(vetor) ou x in vetor
    sleep(1)
    println(sin(x)*cos(x/2)+x," Para x = ",x)
    
    
end

Valor da função sin(x)*cos(x/2)+x:

1.7384602626041288 Para x = 1
2.491295496433882 Para x = 2
3.0099824344694786 Para x = 3
4.314940964313378 Para x = 4
5.768236060439348 Para x = 5


** Percorrendo Uma Matrix ou vetor usando o FOR **

In [19]:
mnum = [2 4;8 9]

2x2 Array{Int64,2}:
 2  4
 8  9

In [20]:
linhas,colunas = size(mnum)

for i = 1:linhas
    
    for j = 1:colunas
        
        println("elemento da linha $i coluna $j é :",mnum[i,j])
    end
end

elemento da linha 1 coluna 1 é :2
elemento da linha 1 coluna 2 é :4
elemento da linha 2 coluna 1 é :8
elemento da linha 2 coluna 2 é :9


Melhorando....

In [21]:
linhas,colunas = size(mnum)

for i = 1:linhas, j = 1:colunas
    println("elemento da linha $i coluna $j é :",mnum[i,j])
end 

elemento da linha 1 coluna 1 é :2
elemento da linha 1 coluna 2 é :4
elemento da linha 2 coluna 1 é :8
elemento da linha 2 coluna 2 é :9


Agora ficou like Python....

In [32]:
# lendo os elementos colunas por colunas 

for i in mnum
    println("elemento  $i")
end

elemento  2
elemento  8
elemento  4
elemento  9


In [34]:
# lendo os elementos linhas por linhas  (coloque aspas simples para inverter a matriz)

for i in mnum'
    println("elemento  $i")
end

elemento  2
elemento  4
elemento  8
elemento  9


**Formas elegantes do laço for**

In [6]:
for n = 1:2
    for m = 1:2
        println("$n * $m = $(n * m)")
    end
end 

1 * 1 = 1
1 * 2 = 2
2 * 1 = 2
2 * 2 = 4


In [36]:
for n = 1:2, m = 1:2
    println("$n * $m = $(n * m)")
end 

1 * 1 = 1
1 * 2 = 2
2 * 1 = 2
2 * 2 = 4


In [2]:
lista = ["julia","python","sagemath","maxima","octave"]

for (index, value) in enumerate(lista)
           println("$index $value")
end

1 julia
2 python
3 sagemath
4 maxima
5 octave


In [38]:
pais = ("Japan", "Korea", "China")
cidade = ("Tokyo", "Seoul", "Pequim")

for (pais, cidade) in zip(pais, cidade)
    println("A capital do $pais é $cidade")
end

A capital do Japan é Tokyo
A capital do Korea é Seoul
A capital do China é Pequim


**List Comprehensions**

Uma compreensão de lista é uma construção sintática disponível em algumas linguagens de programação para criação de uma lista baseada em listas existentes. Ela segue a forma da notação de definição de conjunto matemática (compreensão de conjunto) como forma distinta para uso de funções de mapa e filtro.
***Fonte: wikipedia***

In [27]:
[x^2 for x in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [5]:
[x * y for x in 1:3, y in 3:6]

3x4 Array{Int64,2}:
 3   4   5   6
 6   8  10  12
 9  12  15  18

In [26]:
# a instrução ".>" é necessária para comparar elemento por elemento

x=[1 2 3 4 5 9 25 32 55 510]

[y for y in x[x .> 4]]

6-element Array{Any,1}:
   5
   9
  25
  32
  55
 510

In [31]:
# x = vetor; y = vetor

g(x,y) = x - y

A1 = [ g(x,y) for x in [1 2 3], y = [1 2 3]]

3x3 Array{Int64,2}:
 0  -1  -2
 1   0  -1
 2   1   0

In [62]:
# Acessar o elemento da primeira linha e terceira coluna

A[1,3]

-2

In [7]:
# x in ; y in

A2 = [g(x,y) for x in [1 2 3], y in [1 2 3]]

3x3 Array{Int64,2}:
 0  -1  -2
 1   0  -1
 2   1   0

In [4]:
x = [10 11 12 13 14 15 16 17]

[ x[i] + x[i-1] for i=2:length(x) ]

7-element Array{Any,1}:
 21
 23
 25
 27
 29
 31
 33

In [58]:
sq = [x*x for x in filter(x -> x % 2 == 0, 1:10)]

5-element Array{Any,1}:
   4
  16
  36
  64
 100

In [40]:
[ x + y for x = filter(x -> x <= 2, 1:5), y = filter(isprime,1:5) ]

2x3 Array{Any,2}:
 3  4  6
 4  5  7

** Aplicações**

* **Teste de Benchmark - Método bruto de encontrar raízes de uma função **

In [8]:
# Método bruto de encontrar raízes de uma função

tic()

x = 1.0:0.0000001:5.0;

for k = 1:length(x)
    
    if abs(sin(x[k]).*x[k].^2 + cos(x[k]).*x[k].^2 + x[k] + cos(sin(x[k])).^2) < 0.0000001
        
        println("Valor(y):",sin(x[k]).*x[k].^2+cos(x[k]).*x[k].^2+x[k]+cos(sin(x[k])).^2," . Raiz(x): ",x[k])
        
    end
end

toc();

elapsed time: 40.733054699 seconds


Foi encontrda 3 raízes: 2.70499, 5.35325 e 8.726468

* **Método de Gauss**

In [17]:
#********** PROGRAMA ELIMINAÇÃO PELO MÉTODO DE GAUSS ************* 

A = [4.1 -5.4 6.8;7.8 -8 -9;-17 4 1] # use numeros decimais mesmo que sejam inteiros
b = [1.0,2.0,3.0]                    # use numeros decimais mesmo que sejam inteiros

x = zeros(3) # pré alocação da matrix x
m = 0
al,ac = size(A)

#********** ESCALONAMENTO ************* 

# Aqui é escolhido o pivo e a matriz é escalonada

for k= 1:(al-1)
    
    for i = (k+1):al
       
        m = A[i,k]/(A[k,k])
        A[i,k] = 0
        for j=(k+1):al
            
            A[i,j] = A[i,j] - m*A[k,j]
            b[i]= b[i] - m*b[k]
        end
    end
end

# aqui os valores do vetor solução X são calculados

x[al] = b[al]/(A[al,al])

for k = (al-1):-1:1
    begin
        s = 0
        for j = (k+1):al
            s = s+A[k,j]*x[j]
        end
        x[k]=(b[k]-s)/A[k,k]
    end
end

println(x)

[-0.5552084480553038,-0.5786297325460229,0.022316776658561962]


<strong>Repetição "ENQUANTO" (WHILE) </strong>

<p style="text-align: justify;"><strong>Repetição "WHILE"<br>
</strong></p>
<p style="text-align: justify;"><strong></strong></p>
<table
style="text-align: left; width: 284px; height: 146px; margin-left: 0px; margin-right: 0px;"
border="1" cellpadding="2" cellspacing="1">
<tbody>
<tr>
<td colspan="1" rowspan="1"
style="vertical-align: top; text-align: left;">&nbsp;<span
style="font-weight: bold;">while</span> condicao<br>
&nbsp;&nbsp;&nbsp;&nbsp; instruções;<br>
&nbsp;<span style="font-weight: bold;">end</span><span
style="font-weight: bold;"></span><span style="font-weight: bold;"><br>
</span></td>
<td style="vertical-align: top;"><span style="font-weight: bold;">while</span>
condicao<br>
&nbsp;&nbsp;&nbsp;&nbsp; instruções;<br>
&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">if</span>
condição<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span
style="font-weight: bold;">continue ou break;</span><br>
&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: bold;">end<br>
end</span><span style="font-weight: bold;"></span><span style="font-weight: bold;">
</span></td>
</tr>
</tbody>
</table>

In [41]:
# conta enquanto "a" menor ou igual a 5.
a = 0

while a <= 5
    
    println(a)
    a = a+1
    
end

0
1
2
3
4
5


In [42]:
# conta enquanto "a" menor ou igual a 5. 
# se "a" dividido por 3 for diferente de 0 para!

a = 0

while a <= 10
    
    println(a)
    a = a + 1
    
    if a % 3 == 0
        break
    end
    
end

0
1
2


** Aplicações **

* Método da Bisseção

In [ ]:
tic()
"""
Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.

adaptado de http://goo.gl/pQNh6z 
"""
f(x) = x^2 - 4*x
a = 1
b = 3
tol = 0.00000001
iteracao = 0
    
    while b - a >= tol
        
    x_medio = (a + b)/2.0
        
    println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
        
    if (x_medio^2 - 2*x_medio)*(a^2 - 2*a) > 0.0
            a = x_medio            
        else
            b = x_medio            
        end
        iteracao = iteracao + 1
end
    x_medio = (a + b)/2.0
    
println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
    
toc();

### REPETIÇÃO "FAÇA ATÉ QUE" (DO...UNTIL) ###

<strong>Repetição "DO... UNTIL"<br>
</strong></p>
<p style="text-align: justify;"><strong></strong></p>
<table
style="text-align: left; width: 329px; height: 130px; margin-left: 0px; margin-right: 0px;"
border="1" cellpadding="2" cellspacing="1">
<tbody>
<tr>
<td colspan="1" rowspan="1"
style="vertical-align: top; text-align: left;">&nbsp;<span
style="font-weight: bold;"></span><span style="font-weight: bold;">do<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>instruções<span
style="font-weight: bold;">;<br>
&nbsp;until (</span>condicao<span style="font-weight: bold;">)<br>
</span></td>
<td style="vertical-align: top;"><span style="font-weight: bold;">do<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>instruções<span
style="font-weight: bold;">;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if </span>condição<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span
style="font-weight: bold;">continue ou break;</span><br>
<span style="font-weight: bold;">&nbsp; &nbsp; &nbsp; end <br>
until (</span>condicao<span style="font-weight: bold;">)</span></td>
</tr>
</tbody>
</table>

In [ ]:
numeros = 1:0.1:20

find(numeros) do valor
    valor == 12.4
end

### FUNÇÕES ( function( ) ) ###

A

* **FUNÇÃO DIMENSÃO DE UMA MATRIX **

In [9]:
function fmatrixD(M)
    println("------------ inicio funcao -----------")
    
    display(M)    
        
    println("a dimensão da matriz é :",size(M))
    
    println("--------------- fim -----------------")
    
end

fmatrixD (generic function with 1 method)

In [10]:
fmatrixD([1 1 2 ; 4 8 9])

------------ inicio funcao -----------


2x3 Array{Int64,2}:
 1  1  2
 4  8  9

a dimensão da matriz é :(2,3)
--------------- fim -----------------


* ** FUNÇÃO CÁLCULO DA ÁREA DE UM CÍRCULO **

In [11]:
function area(raio)
  areaCirc = pi * raio^2
    println("A área vale: ", round(areaCirc,5),"m²" )
end

area (generic function with 1 method)

In [12]:
area(2)

A área vale: 12.56637m²


* ** FUNÇÃO RAIZES DE UMA FUNÇÃO DO SEGUNDO GRAU**

In [43]:
function fraiz(a,b,c)
    
    d = (b^2) - (4*a*c)
    
    if d < 0
        print("Delta negativo, raiz real impossivel de ser extraida.")
        
    else
        println("Delta: ",d)
        
        x1 = (-b + sqrt(d)) / (2*a)
        x2 = (-b - sqrt(d)) / (2*a)
        
        println("Raiz X1 = ", x1)
        println("Raiz X2 = ", x2)
    end
end

fraiz (generic function with 1 method)

In [45]:
# entre com os coeficientes da função do segundo grau

fraiz(2,1,-3)

Delta: 25
Raiz X1 = 1.0
Raiz X2 = -1.5


* ** FUNÇÃO MET BISSEÇÃO **

Função Método da Bisseção

In [7]:
"""
Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.

"""

function fmetbissec(a,b,tol)

f(x) = x^2-4*x

iteracao = 0
    
    while b - a >= tol
        
    x_medio = (a + b)/2.0
        
    println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
        
    if (x_medio^2 - 2*x_medio)*(a^2 - 2*a) > 0.0
            a = x_medio            
        else
            b = x_medio            
        end
        iteracao = iteracao + 1
end
    x_medio = (a + b)/2.0
    
println("interação: ", iteracao , " : ", x_medio, ", valor função: ",x_medio^2 - 2*x_medio)
       
end

fmetbissec (generic function with 1 method)

In [9]:
fmetbissec(1.5,2.5,0.00001)

interação: 0 : 2.0, valor função: 0.0
interação: 1 : 1.75, valor função: -0.4375
interação: 2 : 1.875, valor função: -0.234375
interação: 3 : 1.9375, valor função: -0.12109375
interação: 4 : 1.96875, valor função: -0.0615234375
interação: 5 : 1.984375, valor função: -0.031005859375
interação: 6 : 1.9921875, valor função: -0.01556396484375
interação: 7 : 1.99609375, valor função: -0.0077972412109375
interação: 8 : 1.998046875, valor função: -0.003902435302734375
interação: 9 : 1.9990234375, valor função: -0.0019521713256835938
interação: 10 : 1.99951171875, valor função: -0.0009763240814208984
interação: 11 : 1.999755859375, valor função: -0.0004882216453552246
interação: 12 : 1.9998779296875, valor função: -0.00024412572383880615
interação: 13 : 1.99993896484375, valor função: -0.00012206658720970154
interação: 14 : 1.999969482421875, valor função: -6.1034224927425385e-5
interação: 15 : 1.9999847412109375, valor função: -3.0517345294356346e-5
interação: 16 : 1.9999923706054688, valor f

Para ler o cabeçalho da função use: ? metbissec

In [13]:
? fmetbissec

search: fmetbissec



Metodo da Bisseccao

Calcula uma aproximação para uma raiz da função de f(x)

Entre os intervalo [ao,bo] e a tolerencia de erro daddo por tol.


* **Função série de Fibonacci ** 

In [45]:
function fiboR(n) 
    if n < 2 
        return n
    else
        fiboR(n-1) + fiboR(n-2)
    end
end

fiboR (generic function with 1 method)

In [46]:
@time fiboR(35)

  0.099072 seconds (697 allocations: 37.531 KB)


9227465

#### IMPORTANDO FUNÇÕES ".jl  ####

O código deve ser escrito em um arquivo com a extensão ".jl" e importado usando a função ** include("arquivo.jl") **

In [43]:
include("ffiboR_JL.jl")

ffiboR_JL (generic function with 1 method)

In [44]:
@time ffiboR_JL(40)

  1.077163 seconds (753 allocations: 41.139 KB)


102334155

** % FIM PROGRAMAÇÃO BÁSICA % **